# Permalinks
permalink:           pretty

# Setup
title:               Jon Hall
tagline:             "Words & waffle"
url:                 https://jall.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jon Hall
  url:               https://twitter.com/jonnyrhall
  email:             jon@flowmo.co

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jall/jall

# Analytics
analytics_id: "UA-85718087-1"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
